remote_theme: pmarsceill/just-the-docs
title: JJANGDOLL
description: "JJANGDOLL's Ark"
url: "https://jjangdoll.github.io"

aux_links:
  "JJANGDOLL on GitHub":
    - "https://github.com/JJANGDOLL"
aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark

markdown: kramdown

exclude: ["README.md"]

defaults:
  values:
    mathjax: true

kramdown:
  syntax_highlighter: rouge

analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-0X0GG2BJ9R"
    #anonymize_ip         : # true, false (default)